fix: huggingface-cpu image - torch version and vllm OpenAIServingChat parameters
core: fix AttributeError: '_OpNamespace' '_C' object has no attribute 'init_cpu_memory_env'
      AttributeError: 'AsyncLLM' object has no attribute 'io_processor'. Did you mean: 'input_processor'

      On vllm 0.20.0 the OpenAIServingChat does not have io_processor or input_processor
      https://github.com/vllm-project/vllm/blob/v0.20.0/vllm/entrypoints/openai/api_server.py#L369-L383

      AttributeError: 'ServingScores' object has no attribute 'do_rerank'
      Previously we had -> https://github.com/vllm-project/vllm/blob/v0.19.0/vllm/entrypoints/pooling/score/serving.py#L541
      Now it was changed, this method was removed and it is now inherited from PoolingServing and move to
      https://github.com/vllm-project/vllm/blob/v0.20.0/vllm/entrypoints/pooling/scoring/serving.py#L68

Signed-off-by: Spolti <fspolti@redhat.com>